config/routes.rb
Rails.application.routes.draw do
  root 'quotes#index'

  resources :quotes, except: [:edit,:update,:destroy] do
    member do
      get :change_rating
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates_presence_of :text, :author_nickname
  validates_length_of :author_nickname, minimum: 2, maximum: 20, allow_blank: false, message: 'длина никнейма должна быть от 2 до 20 символов'
  validates_length_of :text, minimum: 0, maximum: 500, allow_blank: false, message: 'слишком длинное сообщение'
  
  def change_rate diff
    self.rate += diff
    self.save
    self.rate
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    if params[:order] == 'rate'
      @quotes = Quote.order(rate: :desc)
    else
      @quotes = Quote.order(created_at: :desc)
    end
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      flash.notice = "Цитата добавлена"
      redirect_to root_path
    else
      flash.alert = 'Исправьте ошибки'
      render :new
    end
  end

  def change_rating
    @quote = Quote.find params[:id]
    direction = params[:direction]
    unless ['up','down'].include? direction
      render json: { type: 'error', message: 'Ошибка: не передан параметр direction.' }
    else
      session[:rated_quotes] ||= []
      if session[:rated_quotes].include? @quote.id
        render json: { type: 'error', message: 'Вы уже голосовали за эту цитату.' }
      else
        diff = direction == 'up' ? 1 : -1
        new_rate = @quote.change_rate(diff)
        session[:rated_quotes] << @quote.id
        render json: { type: 'success', message: 'Ваш голос учтен.', rate: new_rate }
      end
    end
  end

  private
  def quote_params
    params.require(:quote).permit(
      :text,
      :rate,
      :author_nickname,
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Форматирование даты / времени
  def rus_date date
    date.strftime('%d.%m.%Y') rescue date
  end
  def rus_dtime dtime
    dtime.strftime('%d.%m.%Y %H:%M') rescue dtime
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    meta charset="UTF-8"
    meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"
    - if yield(:seo_title).present?
      title KURILKA || #{yield(:seo_title)}
    - else
      title KURILKA || Свобода слова, свобода мысли!
    meta name="description" content="#{ yield(:seo_description) }"
    meta name="keywords" content="#{ yield(:seo_keys) }"
    link rel="icon" href=asset_path("favicon.ico")
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render 'layouts/partials/loader'
    - ['alert', 'notice'].each do |fl|
      - if flash.send(fl).present?
        #flash-alert class="flash_color_#{ fl }" = flash.send(fl)
    header
      .container-fluid
        .header
          = render 'layouts/partials/header'
    .container-fluid style='padding:0;padding-left:1px'
      .menu-container-fixed-height
        = render 'layouts/partials/menu'
    .content-wrapper
      .row
        .col-sm-6.col-sm-offset-3.col-xs-10.col-xs-offset-1
          = yield
    / - unless (controller_name == 'main' && action_name == 'index')
    /   = render 'layouts/partials/footer'
    / - ['alert', 'notice'].each do |fl|
    /   - if flash.send(fl).present?
    /     #flash-alert class="flash_color_#{ fl }" = flash.send(fl)

app/views/layouts/partials/_footer.html.slim
#footer
  span#first-footer-span.padding-right-30 Kurilka © 2019
  span
    |Built by 
    a.underline-border href='https://vk.com/aleko_spb' target='blank' Alexey Kozenko
  div#scroll-to-top-button

app/views/layouts/partials/_header.html.slim
.row#header
  .col-sm-4.col-sm-offset-4.text-center
    = link_to root_path
      h2.margin-top-0.margin-bottom-0 Kurilka

app/views/layouts/partials/_loader.html.slim
#loading-state-div
  div.spinner-container
    #logo-loader
      #logo-loader-text
        |K
        span#xs-logo-loader-little urilka
      br
      i.fa.fa-spinner.fa-pulse.fa-5x.fa-fw
        span.sr-only

app/views/layouts/partials/_menu.html.slim
.row#menu.js-fixed-menu
  ul#desktop-menu.nav.navbar-nav
    li
      = link_to 'Новое',quotes_path, class: "category-link#{' active' if action_name == 'index' && !params[:order].present? }"
    li
      = link_to 'Лучшее',quotes_path(order: :rate), class: "category-link#{' active' if action_name == 'index' && params[:order] == 'rate' }"
    li
      = link_to 'Добавить',new_quote_path, class: "category-link#{' active' if action_name == 'new'}"

app/views/layouts/partials/_menu_icon.html.slim
svg#menu-svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" viewBox="0 0 300 400" width='30'
  g
    rect x="0" y="100" width="300" height="14.2857141"
    rect x="0" y="189.9972076" width="300" height="14.2857141"
    rect x="0" y="280.0013885" width="300" height="14.2857141"

app/views/layouts/partials/_mobile_menu.html.slim
#mobile_menu
  ul.nav.navbar-nav
    / - category = Category.find_by_slug("glass")
    / li
    /   = link_to "#{category.title}", category_path(category,locale: get_locale), class: "category-link #{ 'active' if params[:id] == category.slug || (@product.present? && @product.category.slug == 'glass') }", data: { category: "#{category.slug}" }
    - category = Category.find_by_slug("textile")
    li
      = link_to "#{category.title}", category_path(category,locale: get_locale), class: "category-link #{ 'active' if params[:id] == category.slug || (@product.present? && @product.category.slug == 'textile') }", data: { category: "#{category.slug}" }
    - category = Category.find_by_slug("metal")
    li
      = link_to "#{category.title}", category_path(category,locale: get_locale), class: "category-link #{ 'active' if params[:id] == category.slug || (@product.present? && @product.category.slug == 'metal') }", data: { category: "#{category.slug}" }
    li
      = link_to(contacts_path(locale: get_locale), class: "category-link contacts-link #{ 'active' if controller_name == 'main' && action_name == 'contacts' }")
        |Контакты
    li
      = active_link_to 'RU', change_locale_url(nil), active: :exclusive, class: "locale_link"
      | &nbsp;/&nbsp;
      = active_link_to 'EN', change_locale_url('en'), class: "locale_link"

app/views/quotes/_form.html.slim
= simple_form_for @quote, html: { class: 'form-horizontal' } do |f|
  = f.input :text
  = f.input :author_nickname
  .text-center.margin-top-40.margin-bottom-40
    = f.submit 'Сохранить', class: 'btn btn-lg btn-default flat'

app/views/quotes/_quote_block.html.slim
.quote__block data-quote-id="#{ quote.id }"
  .quote__header
    .quote__header_author = quote.author_nickname
    .quote__header_date = rus_dtime quote.created_at
  .quote__body.whitespacer
    = quote.text
  .quote__footer
    .text-center.full-width
      = link_to 'javascript:void(0);', class: 'rate_toggler', data: { direction: 'down' }
        i.fa.fa-thumbs-down.margin-right-30
      span.quote__footer_counter = quote.rate
      = link_to 'javascript:void(0);', class: 'rate_toggler', data: { direction: 'up' }
        i.fa.fa-thumbs-up.margin-left-30

app/views/quotes/index.html.slim
= content_for :seo_title
  | Главная

= content_for :seo_description
  | Kurilka. Цитатник этих ваших интернетов
- for quote in @quotes
  = render 'quote_block', quote: quote

app/views/quotes/new.html.slim
= content_for :seo_title
  | Добавить цитату

= content_for :seo_description
  | Kurilka. Добавить новую цитату

= render 'form'